### ISSUE TITLE
GameServices/texts-es-ES and GameServices/texts-es-Es

### ISSUE THREAD

**Issue by nfearnley** [NYRDS/remixed-dungeon#169]
The repo has two copies of this folder, with different cases. This breaks cloning the repo onto case-insensitive systems. I have tried to determined where this file is used, and I cannot find any reference to it in the code. How are these locale files used in the app?

**Comment by Mikhael-Danilov** [comment]
Content of GameServices not used directly by app code but contain resources for Google Play app store listing and so on.
GameServices/texts-es-Es was an error, so I removed it.
