### ISSUE TITLE
Feature Request: Non-Play Store builds

### ISSUE THREAD

**Issue by Mokura** [NYRDS/remixed-dungeon#2719]
EDIT: Just noticed the downloads on the NYRDS wiki.  Editing issue to adjust.

Would it be possible to get downloads for the game that don't require the Play Store?  Perhaps on something like [F-Droid](https://f-droid.org/) or [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/info)?

**Comment by Mikhael-Danilov** [comment]
Most recent builds cloud be obtained on https://discord.gg/gQb2uRQdYx  (wiki updated manually, so it lags a bit)

Release on additional platforms is nice indeed, although not a top priority at the time, as it will require a specific build (current build depends on a bunch of Google libraries most of which will be considered an anti-feature on F-Droid), which in turn require additional changes in Remixed - it should be buildable for say Google Play and F-Droid from same codebase. (I tried to do something alike: https://github.com/NYRDS/remixed-dungeon/blob/fe0dee09c1146c58b54f4d3eb919d998b01df21e/RemixedDungeon/build.gradle#L81 yet was unable to find enough time to finish.)

**Comment by Mokura** [comment]
I don't expect a company, even with an open source (and ad-supported) game, to make an ad-less/offline version.  But would there be difficulties in removing the various ad and Google connection code?  I'm assuming there are small banners that affect UI dimensions, options for buttons in some windows (I think the on-death window, maybe?) and interstitials on game load.  For removing Play Games interaction, it could either be removed, or replaced with an import/export system (far more complicated, imo)

Thoughts?

**Comment by Mikhael-Danilov** [comment]
No difficulties, just time which I'm currently short of. So it not very likely to be done soon. I'll however gladly PR which improve compatibility with other platforms.

**Comment by Mikhael-Danilov** [comment]
I managed to setup github ci - https://github.com/NYRDS/remixed-dungeon/actions - it builds apks without any closed source dependencies, at least I believe so. It still a bit messy, and not guaranteed to be stable, but it is here.
