### ISSUE TITLE
[HELP NEEDED] Can't use emulator - too slow

### ISSUE THREAD

**Issue by swooboo** [NYRDS/remixed-dungeon#50]
While everything runs smoothly on my work computer (Lenovo T470p) without any performance issues / lag / etc., on my home laptop (Lenovo Legion Y720), all the emulators I tried (and I tried a lot, BlueStacks and MeMu among them) are slow and unusable (virtually stuck). Also the CPU usage on T470p is usually ~100% when using an emulator, while on the Legion it doesn't scratch the 5% mark.

Anybody got an idea on how to fix this?

**Comment by Mikhael-Danilov** [comment]
Lets chose android emulator bundled with android studio as baseline. 
Make sure you use x86 image and HAXM emulator
Make sure CPU virtualization features enabled in bios|uefi
Allow emulator to use multiple cpu cores and fair amout of ram
