### ISSUE TITLE
korean translation

### ISSUE THREAD

**Issue by namjisu** [NYRDS/remixed-dungeon#97]
Hello! I am a Korean who is interested in this program. 
I heard it's localized, but as a Korean, I'm sad that there's no Korean translation.
If you are interested in the Korean version, I will help you translate it into Korean. 
I'd appreciate it if you could be positive about the proposal.

**Comment by Mikhael-Danilov** [comment]
Hi!
Actually there is Korean translation.
Take a look to:
https://github.com/NYRDS/remixed-dungeon/blob/master/RemixedDungeon/src/main/res/values-ko/strings_all.xml
And
https://www.transifex.com/nyrds/remixed-dungeon/language/ko/

Any help  is welcome.
